
package calculadorafinal;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;


public class Formulario extends javax.swing.JFrame {
    double N1 = 0; 
    double N2 = 0; 
    String operador = ""; 
    boolean esResultado = false;
    
    public Formulario() {
        initComponents();
        jTextField1.requestFocusInWindow();
        jTextField1.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent evt) {
                char c = evt.getKeyChar();
                if (c =='0') {
                    jTextField1.setText(jTextField1.getText() + "0");
                }else if(c=='1'){
                    jTextField1.setText(jTextField1.getText() + "1");
                }else if(c=='2'){
                    jTextField1.setText(jTextField1.getText() + "2");
                }else if(c=='3'){
                    jTextField1.setText(jTextField1.getText() + "3");
                }else if(c=='4'){
                    jTextField1.setText(jTextField1.getText() + "4");
                }else if(c=='5'){
                    jTextField1.setText(jTextField1.getText() + "5");
                }else if(c=='6'){
                    jTextField1.setText(jTextField1.getText() + "6");
                }else if(c=='7'){
                    jTextField1.setText(jTextField1.getText() + "7");
                }else if(c=='8'){
                    jTextField1.setText(jTextField1.getText() + "8");
                }else if(c=='9'){
                    jTextField1.setText(jTextField1.getText() + "9");
                }else if(c=='.'){
                    jTextField1.setText(jTextField1.getText() + ".");
                }else if(c=='+'){
                operador = String.valueOf(c);
                N1 = Double.parseDouble(jTextField1.getText());
                jTextField1.setText("");
               
                }else if(c=='-'){
                operador = String.valueOf(c);
                N1 = Double.parseDouble(jTextField1.getText());
                jTextField1.setText("");
                }else if(c=='*'){
                operador = String.valueOf(c);
                N1 = Double.parseDouble(jTextField1.getText());
                jTextField1.setText("");
                }else if(c=='/'){
                operador = String.valueOf(c);
                N1 = Double.parseDouble(jTextField1.getText());
                jTextField1.setText("");
                }else if(c=='='|| c == KeyEvent.VK_ENTER){
                  BIGUALActionPerformed(null);
                }
                evt.consume();  
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        BENTRE = new javax.swing.JButton();
        BPOR = new javax.swing.JButton();
        BORRAR = new javax.swing.JButton();
        BCERRAR = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        BMENOS = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        BMAS = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        BIGUAL = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        BPUNTO = new javax.swing.JButton();
        B0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setBorder(null);

        BENTRE.setBackground(new java.awt.Color(102, 102, 102));
        BENTRE.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        BENTRE.setForeground(new java.awt.Color(255, 255, 255));
        BENTRE.setText("/");
        BENTRE.setBorder(null);
        BENTRE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BENTREMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BENTREMouseReleased(evt);
            }
        });
        BENTRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BENTREActionPerformed(evt);
            }
        });

        BPOR.setBackground(new java.awt.Color(102, 102, 102));
        BPOR.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        BPOR.setForeground(new java.awt.Color(255, 255, 255));
        BPOR.setText("*");
        BPOR.setBorder(null);
        BPOR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BPORMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BPORMouseReleased(evt);
            }
        });
        BPOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPORActionPerformed(evt);
            }
        });

        BORRAR.setBackground(new java.awt.Color(0, 0, 153));
        BORRAR.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        BORRAR.setForeground(new java.awt.Color(255, 255, 255));
        BORRAR.setText("Bor..");
        BORRAR.setBorder(null);
        BORRAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BORRARMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BORRARMouseReleased(evt);
            }
        });
        BORRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BORRARActionPerformed(evt);
            }
        });

        BCERRAR.setBackground(new java.awt.Color(102, 102, 102));
        BCERRAR.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        BCERRAR.setForeground(new java.awt.Color(255, 255, 255));
        BCERRAR.setText("CE");
        BCERRAR.setBorder(null);
        BCERRAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BCERRARMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BCERRARMouseReleased(evt);
            }
        });
        BCERRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCERRARActionPerformed(evt);
            }
        });

        B8.setBackground(new java.awt.Color(102, 102, 102));
        B8.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        B8.setForeground(new java.awt.Color(255, 255, 255));
        B8.setText("8");
        B8.setBorder(null);
        B8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B8MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                B8MouseReleased(evt);
            }
        });
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });

        B9.setBackground(new java.awt.Color(102, 102, 102));
        B9.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        B9.setForeground(new java.awt.Color(255, 255, 255));
        B9.setText("9");
        B9.setBorder(null);
        B9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B9MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                B9MouseReleased(evt);
            }
        });
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });

        BMENOS.setBackground(new java.awt.Color(102, 102, 102));
        BMENOS.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        BMENOS.setForeground(new java.awt.Color(255, 255, 255));
        BMENOS.setText("-");
        BMENOS.setBorder(null);
        BMENOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BMENOSMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BMENOSMouseReleased(evt);
            }
        });
        BMENOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMENOSActionPerformed(evt);
            }
        });

        B7.setBackground(new java.awt.Color(102, 102, 102));
        B7.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        B7.setForeground(new java.awt.Color(255, 255, 255));
        B7.setText("7");
        B7.setBorder(null);
        B7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                B7MouseReleased(evt);
            }
        });
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });

        B5.setBackground(new java.awt.Color(102, 102, 102));
        B5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        B5.setForeground(new java.awt.Color(255, 255, 255));
        B5.setText("5");
        B5.setBorder(null);
        B5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                B5MouseReleased(evt);
            }
        });
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        B6.setBackground(new java.awt.Color(102, 102, 102));
        B6.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        B6.setForeground(new java.awt.Color(255, 255, 255));
        B6.setText("6");
        B6.setBorder(null);
        B6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                B6MouseReleased(evt);
            }
        });
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });

        BMAS.setBackground(new java.awt.Color(102, 102, 102));
        BMAS.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        BMAS.setForeground(new java.awt.Color(255, 255, 255));
        BMAS.setText("+");
        BMAS.setBorder(null);
        BMAS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BMASMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BMASMouseReleased(evt);
            }
        });
        BMAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMASActionPerformed(evt);
            }
        });

        B4.setBackground(new java.awt.Color(102, 102, 102));
        B4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        B4.setForeground(new java.awt.Color(255, 255, 255));
        B4.setText("4");
        B4.setBorder(null);
        B4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                B4MouseReleased(evt);
            }
        });
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        B2.setBackground(new java.awt.Color(102, 102, 102));
        B2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        B2.setForeground(new java.awt.Color(255, 255, 255));
        B2.setText("2");
        B2.setBorder(null);
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                B2MouseReleased(evt);
            }
        });
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B3.setBackground(new java.awt.Color(102, 102, 102));
        B3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        B3.setForeground(new java.awt.Color(255, 255, 255));
        B3.setText("3");
        B3.setBorder(null);
        B3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                B3MouseReleased(evt);
            }
        });
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        BIGUAL.setBackground(new java.awt.Color(255, 153, 0));
        BIGUAL.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        BIGUAL.setForeground(new java.awt.Color(255, 255, 255));
        BIGUAL.setText("=");
        BIGUAL.setBorder(null);
        BIGUAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BIGUALMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BIGUALMouseReleased(evt);
            }
        });
        BIGUAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIGUALActionPerformed(evt);
            }
        });

        B1.setBackground(new java.awt.Color(102, 102, 102));
        B1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        B1.setForeground(new java.awt.Color(255, 255, 255));
        B1.setText("1");
        B1.setBorder(null);
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                B1MouseReleased(evt);
            }
        });
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        BPUNTO.setBackground(new java.awt.Color(102, 102, 102));
        BPUNTO.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        BPUNTO.setForeground(new java.awt.Color(255, 255, 255));
        BPUNTO.setText(".");
        BPUNTO.setBorder(null);
        BPUNTO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BPUNTOMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BPUNTOMouseReleased(evt);
            }
        });
        BPUNTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPUNTOActionPerformed(evt);
            }
        });

        B0.setBackground(new java.awt.Color(102, 102, 102));
        B0.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        B0.setForeground(new java.awt.Color(255, 255, 255));
        B0.setText("0");
        B0.setBorder(null);
        B0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B0MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                B0MouseReleased(evt);
            }
        });
        B0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BMENOS, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BMAS, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(B0, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BPUNTO, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BIGUAL, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BCERRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BENTRE, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BPOR, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BORRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BCERRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BENTRE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BPOR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BORRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BMENOS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BMAS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B0, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BPUNTO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BIGUAL, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BPUNTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPUNTOActionPerformed
        jTextField1.setText(jTextField1.getText() + ".");
        jTextField1.requestFocusInWindow();
    }//GEN-LAST:event_BPUNTOActionPerformed

    private void B0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0ActionPerformed
          jTextField1.setText(jTextField1.getText() + "0");
          jTextField1.requestFocusInWindow();
    }//GEN-LAST:event_B0ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
          jTextField1.setText(jTextField1.getText() + "1");
          jTextField1.requestFocusInWindow();
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
          jTextField1.setText(jTextField1.getText() + "2");
          jTextField1.requestFocusInWindow();
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
          jTextField1.setText(jTextField1.getText() + "3");
          jTextField1.requestFocusInWindow();
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
          jTextField1.setText(jTextField1.getText() + "4");
          jTextField1.requestFocusInWindow();
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
      jTextField1.setText(jTextField1.getText() + "5");
      jTextField1.requestFocusInWindow();
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
       jTextField1.setText(jTextField1.getText() + "6");
       jTextField1.requestFocusInWindow();
    }//GEN-LAST:event_B6ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
          jTextField1.setText(jTextField1.getText() + "7");
          jTextField1.requestFocusInWindow();
    }//GEN-LAST:event_B7ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        jTextField1.setText(jTextField1.getText() + "8");
        jTextField1.requestFocusInWindow();
    }//GEN-LAST:event_B8ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
          jTextField1.setText(jTextField1.getText() + "9");
          jTextField1.requestFocusInWindow();
    }//GEN-LAST:event_B9ActionPerformed

    private void BMASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMASActionPerformed
       if (this.jTextField1.getText().isEmpty()) {
        return; 
    }
    if (!operador.isEmpty()) {
        BIGUALActionPerformed(null);
    }
    N1 = Double.parseDouble(this.jTextField1.getText());
    operador = "+";
    this.jTextField1.setText(""); 
    jTextField1.requestFocusInWindow(); 
    }//GEN-LAST:event_BMASActionPerformed

    private void BMENOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMENOSActionPerformed
       if (this.jTextField1.getText().isEmpty()) {
        return; 
    }
    if (!operador.isEmpty()) {
        BIGUALActionPerformed(null);
    }
    N1 = Double.parseDouble(this.jTextField1.getText());
    operador = "-";
    this.jTextField1.setText(""); 
    jTextField1.requestFocusInWindow(); 
    }//GEN-LAST:event_BMENOSActionPerformed

    private void BPORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPORActionPerformed
         if (this.jTextField1.getText().isEmpty()) {
        return; 
    }
    if (!operador.isEmpty()) {
        BIGUALActionPerformed(null);
    }
    N1 = Double.parseDouble(this.jTextField1.getText());
    operador = "*";
    this.jTextField1.setText(""); 
    jTextField1.requestFocusInWindow(); 
    }//GEN-LAST:event_BPORActionPerformed

    private void BENTREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BENTREActionPerformed
      if (this.jTextField1.getText().isEmpty()) {
        return; 
    }
    if (!operador.isEmpty()) {
        BIGUALActionPerformed(null);
    }
    N1 = Double.parseDouble(this.jTextField1.getText());
    operador = "/";
    this.jTextField1.setText(""); 
    jTextField1.requestFocusInWindow(); 
    }//GEN-LAST:event_BENTREActionPerformed

    private void BORRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BORRARActionPerformed
   if (esResultado) {
        this.jTextField1.setText("");
        esResultado = false;  
    } else {
        String textoActual = this.jTextField1.getText();
        if (textoActual.length() > 0) {
            this.jTextField1.setText(textoActual.substring(0, textoActual.length() - 1));
        }
    }
     jTextField1.requestFocusInWindow();
    }//GEN-LAST:event_BORRARActionPerformed

    private void BCERRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCERRARActionPerformed
    N1 = 0;
    N2 = 0;
    operador = "";
    this.jTextField1.setText(""); 
    jTextField1.requestFocusInWindow();
    }//GEN-LAST:event_BCERRARActionPerformed

    private void BIGUALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIGUALActionPerformed
        jTextField1.requestFocusInWindow();
        if (!operador.isEmpty()) {
            N2 = Double.parseDouble(this.jTextField1.getText());
            switch (operador) {
                case "+":
                    N1 += N2;
                  
                    break;
                case "-":
                    N1 -= N2;
                    
                    break;
                case "*":
                    N1 *= N2;
                   
                    break;
                case "/":
                    if (N2 != 0) {
                        N1 /= N2;
                    } else {
                        this.jTextField1.setText("Error");
                        return;
                    }
                    break;
                default:
                    N1 = N2; 
                    break;
            }


            if (N1 == (int) N1) {
                this.jTextField1.setText(String.valueOf((int) N1));
            } else {
                DecimalFormat df = new DecimalFormat("#.##");
                this.jTextField1.setText(df.format(N1));
            }
            N2 = 0;
            operador = "";
            jTextField1.requestFocusInWindow();
            esResultado = true;
        }
    }//GEN-LAST:event_BIGUALActionPerformed

    private void B0MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B0MousePressed
       B0.setBackground(java.awt.Color.blue); 
    }//GEN-LAST:event_B0MousePressed

    private void B0MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B0MouseReleased
        B0.setBackground(java.awt.Color.GRAY); 
    }//GEN-LAST:event_B0MouseReleased

    private void BPUNTOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BPUNTOMousePressed
        BPUNTO.setBackground(java.awt.Color.blue); 
    }//GEN-LAST:event_BPUNTOMousePressed

    private void BPUNTOMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BPUNTOMouseReleased
        BPUNTO.setBackground(java.awt.Color.GRAY); 
    }//GEN-LAST:event_BPUNTOMouseReleased

    private void BIGUALMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BIGUALMousePressed
        BIGUAL.setBackground(java.awt.Color.RED); 
    }//GEN-LAST:event_BIGUALMousePressed

    private void BIGUALMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BIGUALMouseReleased
         BIGUAL.setBackground(java.awt.Color.ORANGE); 
    }//GEN-LAST:event_BIGUALMouseReleased

    private void B1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseReleased
        B1.setBackground(java.awt.Color.GRAY); 
    }//GEN-LAST:event_B1MouseReleased

    private void B1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MousePressed
      B1.setBackground(java.awt.Color.blue); 
    }//GEN-LAST:event_B1MousePressed

    private void B2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MousePressed
       B2.setBackground(java.awt.Color.blue); 
    }//GEN-LAST:event_B2MousePressed

    private void B2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseReleased
           B2.setBackground(java.awt.Color.GRAY); 
    }//GEN-LAST:event_B2MouseReleased

    private void B3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MousePressed
       B3.setBackground(java.awt.Color.blue); 
    }//GEN-LAST:event_B3MousePressed

    private void B3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MouseReleased
       B3.setBackground(java.awt.Color.GRAY); 
    }//GEN-LAST:event_B3MouseReleased

    private void B4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4MouseReleased
        B4.setBackground(java.awt.Color.GRAY); 
    }//GEN-LAST:event_B4MouseReleased

    private void B4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4MousePressed
        B4.setBackground(java.awt.Color.blue); 
    }//GEN-LAST:event_B4MousePressed

    private void B5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5MouseReleased
         B5.setBackground(java.awt.Color.GRAY); 
    }//GEN-LAST:event_B5MouseReleased

    private void B5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5MousePressed
        B5.setBackground(java.awt.Color.blue); 
    }//GEN-LAST:event_B5MousePressed

    private void B6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6MousePressed
       B6.setBackground(java.awt.Color.blue); 
    }//GEN-LAST:event_B6MousePressed

    private void B6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6MouseReleased
        B6.setBackground(java.awt.Color.GRAY); 
    }//GEN-LAST:event_B6MouseReleased

    private void BMASMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BMASMousePressed
       BMAS.setBackground(java.awt.Color.blue); 
    }//GEN-LAST:event_BMASMousePressed

    private void BMASMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BMASMouseReleased
         BMAS.setBackground(java.awt.Color.GRAY); 
    }//GEN-LAST:event_BMASMouseReleased

    private void B7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B7MousePressed
        B7.setBackground(java.awt.Color.blue); 
    }//GEN-LAST:event_B7MousePressed

    private void B7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B7MouseReleased
         B7.setBackground(java.awt.Color.GRAY); 
    }//GEN-LAST:event_B7MouseReleased

    private void B8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B8MousePressed
        B8.setBackground(java.awt.Color.blue); 
    }//GEN-LAST:event_B8MousePressed

    private void B8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B8MouseReleased
        B8.setBackground(java.awt.Color.GRAY); 
    }//GEN-LAST:event_B8MouseReleased

    private void B9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B9MousePressed
        B9.setBackground(java.awt.Color.blue); 
    }//GEN-LAST:event_B9MousePressed

    private void B9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B9MouseReleased
         B9.setBackground(java.awt.Color.GRAY); 
    }//GEN-LAST:event_B9MouseReleased

    private void BMENOSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BMENOSMousePressed
        BMENOS.setBackground(java.awt.Color.blue); 
    }//GEN-LAST:event_BMENOSMousePressed

    private void BMENOSMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BMENOSMouseReleased
         BMENOS.setBackground(java.awt.Color.GRAY); 
    }//GEN-LAST:event_BMENOSMouseReleased

    private void BCERRARMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BCERRARMousePressed
      BCERRAR.setBackground(java.awt.Color.RED); 
    }//GEN-LAST:event_BCERRARMousePressed

    private void BCERRARMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BCERRARMouseReleased
       BCERRAR.setBackground(java.awt.Color.GRAY); 
    }//GEN-LAST:event_BCERRARMouseReleased

    private void BENTREMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BENTREMousePressed
        BENTRE.setBackground(java.awt.Color.blue); 
    }//GEN-LAST:event_BENTREMousePressed

    private void BENTREMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BENTREMouseReleased
      BENTRE.setBackground(java.awt.Color.GRAY); 
    }//GEN-LAST:event_BENTREMouseReleased

    private void BPORMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BPORMousePressed
           BPOR.setBackground(java.awt.Color.blue);
    }//GEN-LAST:event_BPORMousePressed

    private void BPORMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BPORMouseReleased
        BPOR.setBackground(java.awt.Color.GRAY); 
    }//GEN-LAST:event_BPORMouseReleased

    private void BORRARMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BORRARMousePressed
         BORRAR.setBackground(java.awt.Color.RED);
    }//GEN-LAST:event_BORRARMousePressed

    private void BORRARMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BORRARMouseReleased
         BORRAR.setBackground(java.awt.Color.blue); 
    }//GEN-LAST:event_BORRARMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B0;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton BCERRAR;
    private javax.swing.JButton BENTRE;
    private javax.swing.JButton BIGUAL;
    private javax.swing.JButton BMAS;
    private javax.swing.JButton BMENOS;
    private javax.swing.JButton BORRAR;
    private javax.swing.JButton BPOR;
    private javax.swing.JButton BPUNTO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
